### ISSUE TITLE
画面によって表示される総合BPIが違う

### ISSUE THREAD

**Issue by sr8e** [BPIManager/BPIManager-Core#25]
## 概要
統計>基本>総合BPIに出てくる総合BPIと、統計>推移>総合BPI推移のグラフに表示される総合BPIが違う(下記画像参照)。
また、[デバッグ情報](https://pastebin.pl/view/cf7ca0b2) に含まれている総合BPIもおそらく上の2つと異なる値になっている

![bpi_1](https://user-images.githubusercontent.com/42915825/173111014-ea0a8979-6574-4003-9e3b-001dd5e3ac13.JPG)
![bpi_2](https://user-images.githubusercontent.com/42915825/173111019-62922030-67a4-40ad-9c27-b36c813a098b.JPG)

## 現象を確認した環境
- Windows 10 / Mozilla Firefox 101.0.1
- Android 10 / Chrome 100.0.4896.79

**Comment by potakusan** [comment]
ご報告ありがとうございます。
https://github.com/BPIManager/BPIManager-Core/commit/53842798d9275ff74561bffd3bd1252ab02b4a3c にて挙動を解決しました。

## 原因

BPIManager ではIndexedDBでスコアデータを管理しており、最新のスコアを[scoresテーブル](https://github.com/BPIManager/BPIManager-Core/blob/master/src/components/indexedDB/db/scores.tsx)、スコアログは[scoresHistoryテーブル](https://github.com/BPIManager/BPIManager-Core/blob/master/src/components/indexedDB/db/scoreHistory.tsx)に保存されます。  
しかし定義データ更新時、scoresテーブルは正常に最新のBPIが保存される一方で、scoresHistoryテーブルの中身がうまく更新されておりませんでした。  
そのため、scoresHistoryテーブルを参照し総合BPIを算出する推移グラフが正常な値を取っていませんでした。(基本タブの総合BPIはscoresテーブルを参照するため正常に動作していました)

## 必要な措置

- BPIManager v-85d2884-d86 へのアップデート
