### ISSUE TITLE
単曲スコア表示>バージョン間比較にてBISTROVER,Rootageのスコアが表示されない

### ISSUE THREAD

**Issue by fusso** [BPIManager/BPIManager-Core#31]
### 単曲スコア表示>バージョン間比較にてBISTROVER,Rootageのスコアが表示されない
（共鳴遊戯の華と冥で確認）
![image](https://user-images.githubusercontent.com/65843509/184357133-8d64f747-a568-47c2-9b36-d18ccede2d16.png)

統計>自己歴代にはBISTROVER,Rootageのスコアが反映されていることを確認
![image](https://user-images.githubusercontent.com/65843509/184357274-c819cf93-ad18-4fd2-ac05-8cce39374275.png)

Chrome バージョン: 104.0.5112.81にて確認
デバッグ情報 https://pastebin.com/NVVCpgY0

**Comment by potakusan** [comment]
返信が大変遅れて申し訳ございません。
おそらく原因と思われる箇所を修正いたしましたので報告いたします。

https://github.com/BPIManager/BPIManager-Core/blob/440db89392a6c6413689017b86cf332761319234/src/components/import/execute.tsx#L113

上記にてexScoreに適切でないデータが格納されていました。
(resultHistory[i]は全く別の楽曲のスコアが該当します。)
本来これでは全く適切に動作するはずがないのですが、適切に保存される楽曲が存在する理由までは追っていません。

https://github.com/BPIManager/BPIManager-Core/blob/4ee0b4d6b52a3f9784eb1602ef0a8e92fe7f340d/src/components/import/execute.tsx#L132-L141

これを上記の通り、適切なスコアを保存する仕組みに改善しましたので、今後追加するスコアについては正常に動作します。
今までのデータについては、修正が困難なため対応できなさそうです。申し訳ございませんが、ご了承くださいませ。
